package template

func Docs() string {
	return `*{{lower .Name}}.vim.txt*            For VIM 9.1            Last change: {{now | date "2006-01-02"}}

==============================================================================
Table of Contents                                *{{lower .Name}}.vim-table-of-contents*

1. {{title .Name}}                                                     |{{lower .Name}}.vim-{{lower .Name}}|
  - Installation                                |{{lower .Name}}.vim-{{lower .Name}}-installation|
  - Configuration                              |{{lower .Name}}.vim-{{lower .Name}}-configuration|
  - Commands                                        |{{lower .Name}}.vim-{{lower .Name}}-commands|
  - Docs                                                |{{lower .Name}}.vim-{{lower .Name}}-docs|

==============================================================================
1. {{title .Name}}                                                     *{{lower .Name}}.vim-{{lower .Name}}*


- |{{lower .Name}}.vim-{{lower .Name}}-colorscheme|
    - |{{lower .Name}}.vim-installation|
    - |{{lower .Name}}.vim-configuration|
    - |{{lower .Name}}.vim-commands|
    - |{{lower .Name}}.vim-docs|

    {{title .Name}}


INSTALLATION                                    *{{lower .Name}}.vim-{{lower .Name}}-installation*

>vim
    Plug '{{.Repo}}', { 'branch': 'vim' }
<


CONFIGURATION                                  *{{lower .Name}}.vim-{{lower .Name}}-configuration*

set termguicolors is enabled by default

>vim
    colorscheme {{.Name}}
<


COMMANDS                                            *{{lower .Name}}.vim-{{lower .Name}}-commands*

{{title .Name}}


DOCS                                                    *{{lower .Name}}.vim-{{lower .Name}}-docs*

>vim
    h {{lower .Name}}
<

Generated by yeahboy <https://github.com/maxmx03/yeahboy-colorgen>

vim:tw=78:ts=8:noet:ft=help:norl:
`
}
